### ISSUE TITLE
Unit tests are not working or missing

### ISSUE THREAD

**Issue by dacb** [lmjacoby/ai_semiconductors#2]
I couldn’t find the unit tests or testing framework _or_ they are failing and not working for me.  If you don’t have any, then make sure you justify this decision somewhere, maybe the README.md.  I’m skeptical that any bit of code doesn’t need unit tests.

**Comment by lmjacoby** [comment]
We have also just uploaded unit test files in the past week, and the CI is passing so we believe them to be working.
