### ISSUE TITLE
Repository structure is incomplete or confusing

### ISSUE THREAD

**Issue by dacb** [lmjacoby/ai_semiconductors#3]
Did you follow the standard Python + Git repo structure?  I am struggling to understand all of the pieces of the repo and how they fit together.  You might want to add some information about the repository layout to your `README.md` if you have a non-traditional layout.  Also, there are a few odd files scattered around.

**Comment by lmjacoby** [comment]
We're in the process of reorganizing the repo and putting it in the standard structure (I think). The `README.md` will have more detail in the coming days.
